### ISSUE TITLE
don't add global/skin/global.css to browser

### ISSUE THREAD

**Issue by nightwing** [dhanak/identfavicon#1]
overlay have a line
<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>
which adds new instance of global/skin/global.css to browsers window
creating 2 instances of same stylesheet

**Comment by dhanak** [comment]
Thanks for the report, I'll look into it.

**Comment by dhanak** [comment]
This issue will be fixed in version 0.3.3, which also adds compatibility with FF4.
